### ISSUE TITLE
Update the navbar

### ISSUE THREAD

**Issue by IbrahimDev00** [g-aeroastro-c/gaac-page-f#23]
- [x] 1. Remove EB section from the "Teams" part of the navbar.
- [x] 2. Add appropriate links (redirect the links) to appropriate pages.  (If no page exists, please create a skeleton page, and add a link to it.) 
- [x] 3. Update the links for the various events in events section of the navbar.

**Comment by vvs-basanth** [comment]
I do not see any changes in the navbar section reg. `executivebody team`.
If you alreqdy did that particular change, please do update in a proxy or any other branch so that we do not have conflicting lines when we merge.

**Comment by vvs-basanth** [comment]
I do not see any changes in the navbar section reg. `executivebody team`.
If you alreqdy did that particular change, please do update in a proxy or any other branch so that we do not have conflicting lines when we merge.


Or we can just add scroll effect to the same page when the user clicks on the `Executive Body`.

**Comment by IbrahimDev00** [comment]
I will soon create a PR with a branch named `Revisions`.
That will contain all the changes I've made to all pages.

**Comment by vvs-basanth** [comment]
I guess all three are done?
Shall we close this issue?
